### ISSUE TITLE
LogicalTerminationPoint::_(!)physicalPortReference String -> leafref

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/core#10]
The WireEquipment specification prescribes in chapter Instantiation:LogicalTerminationPoint and LayerProtocol : "The LogicalTerminationPoint::**_**physicalPortReference attribute shall be automatically configured to associate the Equipment object with the LogicalTerminationPoint object."

But LogicalTerminationPoint::physicalPortReference attribute is of String datatype in the Core IM.

Proposed Solution:
UML: Changing the datatype from String towards a shared association
YANG: Changing the type from string towards leafref with require-instance true;

**Comment by openBackhaul** [comment]
YANG has been changed from
```
    leaf-list physical-port-reference {
      type string;
      description
        "One or more text labels for the unmodeled physical port associated with the LTP.
         In many cases there is no associated physical port.";
    }
```
to
```
    leaf-list physical-port-reference {
      type leafref {
        require-instance true;
        path "/core-model:control-construct/core-model:equipment/core-model:uuid";
      }
      description
        "One or more text labels for the unmodeled physical port associated with the LTP.
         In many cases there is no associated physical port.";
    }
```

Issue to remain open until the datatype  has been changed from String towards a shared association in the UML.

**Comment by PrathibaJee** [comment]
- In UML2YANG tool , the pruning and refactoring section of core-model is having the neccessary code changes to change the datatype of the attribute physical-port-reference from **string** to **leafref**. 
- We also generated a [ReleaseCandidate#1](https://github.com/openBackhaul/core/blob/tsp/CoreModel_1.4.1_tsp.211221.1359+yang.2.zip) for the core-model and able to see the leafref statement. 
- But , as per the proposal in [core/issues/17](https://github.com/openBackhaul/core/issues/17) , the require-statement of the leafref shall be "false" and not "true".
```
leaf-list physical-port-reference {
      type leafref {
        path "/core-model:control-construct/core-model:equipment/core-model:uuid";
        require-instance false;
      }
      description
        "One or more text labels for the unmodeled physical port associated with the LTP.
         In many cases there is no associated physical port.";
    }
```
- This will be available if we generate and publish a new release of the core-model-1-4.

> Related issue https://github.com/openBackhaul/core/issues/14

**Comment by michbin** [comment]
I am a little bit confused:
1. The "description" element of the Yang definition shown above does not match the new type nor the intended usage described in the original proposal.
1. IMO the original proposal was later superseded by the ltp-augment model.

**Comment by demx8as6** [comment]
Describing the current status for the core-model related to physical-port-reference from "Release candidate #1"

```
    leaf-list physical-port-reference {
      type leafref {
        path "/core-model:control-construct/core-model:equipment/core-model:uuid";
        require-instance false;
      }
      description
        "One or more text labels for the unmodeled physical port associated with the LTP.
         In many cases there is no associated physical port.";
    }
```

As @michbin pointed the physical-port-reference conflicts with the later add LTP-Augment:

```
    leaf connector {
      type leafref {
        path "/core-model:control-construct/core-model:equipment/core-model:connector/core-model:local-id";
        require-instance false;
      }
      config false;
      description
        "Connector, where this interface (LTP) can be physically connected.";
    }
```

Question: 
- Is a **physical-port-reference(-list)** the same as a **connector**?
  Answer: no but let's try to align
- Do MW devices today and in future have LTPs which require more than one port?
  Answer: no - such complexity exists for optical devices but is not required for MW - therefore, we can say a physical-port- 
  reference-list (as currently modelled) is not needed - a multiplicity of [0..1] would be sufficient for MW model.
- Does it make sense to restrict the reference to "connectors" only and not reference an entire "Equipment"
  Answer: yes it does. 

Bringing all the things together - the pyhsical-port-reference parameter is obsolete and replaced by the LTP-Augment::connector.

Potential Proposal:
- The "pruning and refactoring" step should prune the "LogicalTerminationPoint:physicalPortRefernce[*]". As the result the "physical-port-reference" will be removed from the core-model-1-4.yang.

**Comment by demx8as6** [comment]
**Decision at the 5G-xhaul call on 28th of September 2022:**
- The "pruning and refactoring" step should prune the "LogicalTerminationPoint:physicalPortRefernce[*]". As the result the "physical-port-reference" will be removed from the core-model-1-4.yang.

**Comment by openBackhaul** [comment]
Implemented as decided.
