### ISSUE TITLE
YANG validation errors - key entries do not exist

### ISSUE THREAD

**Issue by alexandrustancu** [openBackhaul/core#11]
The following keys are not defined in the model:
- key "supported-non-fru-typenon-fru-details";
- key "supported-equipment-typefru-details";

It seems like a problem in the YANG generation, looks like some typos there.

This is not reported as a problem by *pyang*, because the lists containing these keys are defined under a grouping that is never used: **grouping support-constraints-g**. So, this could be another issue: defining groupings that are not used in this model.

**Comment by openBackhaul** [comment]
Solution proposed by Alex: Removing the groupings, which are not used.

**Comment by openBackhaul** [comment]
Solution proposed during call:
- Check, whether there is a translation problem with container/leafref
   - If yes, fix to leafref, correct the attributes' names in the key statements, binding in of the logical objects, which are referencing the groupings.
   - If not, just delete the ununsed grouping

**Comment by openBackhaul** [comment]
Decision during 5G xhaul call: delete line 2669 to 2724 in the core-model-1-4.yang

**Comment by openBackhaul** [comment]
Lines 2669 to 2724 have been deleted.
The resulting file has been published as CoreModel_1.4.1_tsp.191122.2040+yang.2
