### ISSUE TITLE
Missing "reference" substatement in "revision" statement

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/core#13]
Validating the Core IM 1.4.1 with pyang --lint core-model.yang
results in 
core-model-1-4.yang:34: error: RFC 8407: 4.8: statement "revision" must have a "reference" substatement

**Comment by PrathibaJee** [comment]
- In UML2YANG tool , the pruning and refactoring section of core-model is having the neccessary code changes to include the "reference" substatement 
```
 revision 2019-11-27 {
    description
      "Package equipment-specification has been deleted,
       because of wrong key statements and overall grouping never applied.";
    reference
      "ONF-TR-512, RFC 6020 and RFC 6087";
  }
```
- We also generated a [ReleaseCandidate#1](https://github.com/openBackhaul/core/blob/tsp/CoreModel_1.4.1_tsp.211221.1359+yang.2.zip) for the core-model and able to see the "reference" substatement. 
- This will be available if we generate and publish a new release of the core-model-1-4.

**Comment by openBackhaul** [comment]
Implemented as decided.
