### ISSUE TITLE
performance-monitoring-is-on on device level required

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/core#16]
It is required to facilitate switching on/off performance monitoring for all interfaces of all technologies at once on device level.

**Comment by michbin** [comment]
This issue needs some clarification:
* Are there any devices which allow enabling/disabling performance data collection on device level only?
* Are there any devices which provide the proposed function in addition to controlling the collection with a finer granularity (e.g. individually per interfaces)?

If yes:
* A new model needs to be created which consists of a configurable attribute and perhaps a capability attribute.

If no:
* The proposed function can be seen as a convenience function which should be provided by the application layer, i.e. by some application or micro service.

**Comment by demx8as6** [comment]
Function not required -> closed
