### ISSUE TITLE
All shared aggregation associations need an additional “require-instance” = false sub-statement.

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#17]
As per the TR531_UML-YANG_Mapping_Gdls_v1.1-1 section 5.6.1 Mapping of associations, "_All navigable pointer and shared aggregation associations need an additional “require-instance” = false sub-statement._" The following attributes will be modified accordingly,

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt;word-wrap:break-word'>

S.No | Attributes
-- | --
1 | encapsulating-casc-port
2 | encompassed-clock
3 | sync-ltp
4 | phase-aligned-clock
5 | lower-level-fd
6 | fc-port/logical-termination-point
7 | lower-level-fc
8 | forwarding-domain/logical-termination-point
9 | fc-port/fc-port
10 | port-of-internal-fc
11 | server-ltp
12 | client-ltp
13 | connected-ltp
14 | peer-ltp
15 | ltp-in-other-view
16 | fd-rule-group
17 | fd-port/logical-termination-point
18 | fd-port/fc-port
19 | fd-port
20 | occupying-fru
21 | top-level-equipment
22 | child-installed-software-component

</body>

</html>

**Comment by PrathibaJee** [comment]
**Discussion on the 5G-xhaul call on 15th of December 2021:**

- UML2YANG tool is having the neccessary code changes to support this enhancement.
- We also generated a core-model and able to see the changes applied to the mentioned attributes.
- This will be available if we publish a new release of the core-model-1-4

**Comment by PrathibaJee** [comment]
As per the recent changes , the above comment is not applicable for encompassed-clock and phase-aligned-clock as they are prunned from the core-model as per the [issue](https://github.com/openBackhaul/core/issues/22).
Additionally , this change will be applicable to the attribute fc-switch/selected-fc-port as this attribute is changed from list to leaf-list as per the [issue](https://github.com/openBackhaul/core/issues/28).

**Comment by openBackhaul** [comment]
Implemented as decided.
