### ISSUE TITLE
Default value inclusion to attributes as per the core-model uml modelling

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#18]
In the published core-model version, we don’t have default values included for the following attributes even though in the uml it is modelled. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt;word-wrap:break-word'>

S.No | Attributes | default values
-- | -- | --
1 | reversion-mode | REVERSION_MODE_REVERTIVE
2 | switch-control | SWITCH_CONTROL_NORMAL
3 | switch-selects-ports | PORT_DIRECTION_INPUT
4 | fc-blocks-signal-to-lp | BLOCK_DIRECTION_NO_BLOCK
5 | is-controlled-fc-port-disabled | FALSE
6 | casc-port/is-protection-lock-out | FALSE
7 | forwarding-construct/ is-protection-lock-out | FALSE
8 | service-priority | 0
9 | fc-port/is-protection-lock-out | FALSE
10 | selection-priority | 0
11 | layer-protocol/is-protection-lock-out | FALSE
12 | is-read-only | FALSE
13 | is-hidden | FALSE

</body>

</html>

**Comment by PrathibaJee** [comment]
**Discussion on the 5G-xhaul call on 15th of December 2021:**

- UML2YANG tool is having the neccessary code changes to include default values for the mentioned attributes.
- We also generated a core-model and able to see the changes applied to the mentioned attributes.
- This will be available if we publish a new release of the core-model-1-4
- To support default value for the attribute fc-blocks-signal-to-lp , unpruned the Typedefinition "BLOCK_DIRECTION".  see dependent issue [issue#19](https://github.com/openBackhaul/core/issues/19)

**Comment by openBackhaul** [comment]
Implemented as decided.
