### ISSUE TITLE
forwarding-construct/fc-port with wrong min-elements

### ISSUE THREAD

**Issue by michbin** [openBackhaul/core#2]
The _fc-port_ list in the _forwarding-construct_ grouping is defined with `min-elements 2`, i.e. must have at least 2 elements.
This is not true for Forwarding Constructs which represent VLANs. They are usually created without member ports which are added afterwards.

**Comment by demx8as6** [comment]
For VLAN purposes I would agree that an "empty" VLAN should be represented as "empty" ForwardingConstuct. 
A solution could be: by "pruning-and-refactoring" the min-elements as defined in CoreModel.UML could be "corrected". 

@openBackhaul: please comment.

**Comment by demx8as6** [comment]
Decision made on the ONF call:
https://wiki.opennetworking.org/display/OTCC/2019-10-30+5G-xHaul+Meeting+Notes

Change min-elements from 2 to 0.

**Comment by demx8as6** [comment]
Please retest once a new core-model was delivered.
![open-backhaul-issue2](https://user-images.githubusercontent.com/9154981/68125809-b3a5ea00-ff12-11e9-8e38-59814a20a38f.png)

**Comment by openBackhaul** [comment]
Minimum number of elements changed to 0.
Issue can be closed.

   ```
 list fc-port {
      key "local-id";
      min-elements 0;
      uses fc-port;
      description
        "The FcPorts define the boundary of the FC.
         The FC is accessed via the FcPorts.
         Flow within the FC is defined in terms of its FcPorts.";
    }
```

**Comment by openBackhaul** [comment]
For avoiding warnings during compilation the "min-elements 0;" statement has been removed.

RFC7950: "If no "min-elements" statement is present, it defaults to zero."
