### ISSUE TITLE
Need to include configuration-and-switch-control grouping to support sync-model

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#20]
To support the augment statement of sync-protection-spec specification in sync-model (mentioned below), need to unprune and include the configuration-and-switch-control grouping.

`augment "/core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:control-parameters" {
    when "derived-from-or-self(/core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:layer-protocol-name, 'sync-model:LAYER_PROTOCOL_NAME_TYPE_SYNCHRONIZATION_LAYER')";
    uses sync-protection-spec;
    description
      "none";
  }
`

**Comment by PrathibaJee** [comment]
**Discussion on the 5G-xhaul call on 15th of December 2021:**

- UML2YANG tool is having the neccessary code changes to include the configuration and switch control grouping.
- We also generated a core-model and able to see the changes. The following entries will be available in the yang,
- This will be available if we publish a new release of the core-model-1-4
```
grouping configuration-and-switch-control {
    leaf switch-rule {
      type string;
      description
        "A sketch of the presence of complex rules governing the switch behavior.";
    }
    list fc-switch {
      key "local-id";
      uses fc-switch;
      description
        "The switch being controlled.";
    }
    container control-parameters {
      uses control-parameters-pac;
      description
        "The control parameters to be applied if local parameters are used rather than profiles.";
    }
    leaf-list profile-proxy {
      type string;
      description
        "Applied profiles.";
    }
    leaf is-frozen {
      type boolean;
      default "false";
      description
        "Temporarily prevents any switch action to be taken and, as such, freezes the current state.
         Until the freeze is cleared, additional near-end external commands are rejected and fault condition changes and received APS messages are ignored.
         All administrative controls of any aspect of protection are rejected.";
    }
    leaf is-coordinated-switching-both-ends {
      type boolean;
      default "false";
      description
        "The C&SC is operating such that switching at both ends of each flow across the FC is coordinated at both ingress and egress ends.";
    }
    leaf-list subordinate-control {
      type leafref {
        path "/core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:switch-rule";
        require-instance false;
      }
      must 'deref(.) = current()';
      description
        "A C&SC that is fully or partially subordinate this C&SC.
         A peer is considered as partially subordinate in that the peer will respond to requests for action from this C&SC but will also make requests for action to be carried out by this C&SC.
         Where there is a peer relationship each controller in the peering will see the other controller as subordinate.";
    }
    leaf-list encapsulated-casc {
      type leafref {
        path "/core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:switch-rule";
        require-instance false;
      }
      must 'deref(.) = current()';
      description
        "Where a C&SC is complex it may be decomposed into subordinate C&SC parts.
         The decomposition is described by the C&SC spec.";
    }
    list casc-port {
      key "uuid";
      uses casc-port;
      description
        "A reference to ports of a C&SC that can be used where there is significant asymmetry to be represented.
         The C&SC need not have ports.";
    }
    leaf-list coordinated-fc {
      type leafref {
        path "/core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:uuid";
        require-instance false;
      }
      description
        "none";
    }
    leaf resilience-control-status {
      type resilience-control;
      description
        "The state of the control process.";
    }
    description
      "Represents the capability to control and coordinate switches, to add/delete/modify FCs and to add/delete/modify LTPs/LPs so as to realize a protection scheme.";
  }
```

**Comment by PrathibaJee** [comment]
As per the proposal in [core-model#issue28](https://github.com/openBackhaul/core/issues/28)  , the configuration-and-switch-control class shall be deleted. 
If this proposal is decided , then in the UML2YANG tool , in the pruning-and-refactoring section, in the pruning-control.xml , the ConfigurationAndSwitchControl should be made prune="true". 
This will prune the ConfigurationAndSwitchControl completely from the generated CoreModel YANG.

**Comment by openBackhaul** [comment]
**Decision made at the 5G-xhaul call on 21st of September 2022:**
The decision made on [15th of December 2021](https://github.com/openBackhaul/core/issues/20#issuecomment-994737226) is in conflict with a later decision in [issue #28](https://github.com/openBackhaul/core/issues/28).
In accordance with decision made in [issue #28](https://github.com/openBackhaul/core/issues/28), grouping configuration-and-switch-control shall not be corrected, but pruned from the modeling.
In accordance with decision made in issue synchronization [issue #47](https://github.com/openBackhaul/synchronization/issues/47), the SyncProtectionSpec class shall be augmented to the Fc :: FcSwitch :: ControlParameters_Pac class, instead of the ConfigurationAndSwitchControl class.

**Comment by openBackhaul** [comment]
Implemented as decided.
