### ISSUE TITLE
Changes to other attributes datatype after including C&SC grouping

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#21]
This change is a consequence of the [issue#20](https://github.com/openBackhaul/core/issues/20).
After including configuration-and-switch-control. The following attributes datatypes are changed to leafref pointing to a CASC instance. Apart from no.3 others are changed intentionally to avoid circular dependency.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/NQ1002~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt;word-wrap:break-word'>

S.No | Attributes | from | to
-- | -- | -- | --
1 | fc-switch/configuration-and-switch-control | string/later casc | /core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:switch-rule
2 | fc-switch/internal-configuration-and-switch-control | string/later casc | /core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:switch-rule
3 | casc-port/encapsulating-casc-port | /core-model:casc-port/core-model:uuid | /core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:casc-port/core-model:uuid
4 | clock/encapsulated-casc | string/later casc | /core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:switch-rule
5 | layer-protocol/configuration-and-switch-control | string/later casc | /core-model:control-construct/core-model:forwarding-domain/core-model:fc/core-model:configuration-and-switch-control/core-model:switch-rule

</body>

</html>

**Comment by PrathibaJee** [comment]
**Discussion on the 5G-xhaul call on 15th of December 2021:**

- UML2YANG tool is having the neccessary code changes to support this datatype change.
- We also generated a core-model and able to see the changes. 
- This will be available if we publish a new release of the core-model-1-4

**Comment by PrathibaJee** [comment]
- As per the proposal in [core-model#issue28](https://github.com/openBackhaul/core/issues/28)  , the configuration-and-switch-control class shall be deleted. 
- If this proposal is decided , then in the UML2YANG tool , in the pruning-and-refactoring section, in the prune-and-refactor-core-model.xslt changes needs to be incorporated to revert the changes.

**Comment by openBackhaul** [comment]
**Decision made at the 5G-xhaul call on 28th of September 2022:**
(_[issue #29](https://github.com/openBackhaul/core/issues/29) to be decided first_)

The decision made on [15th of December 2021](https://github.com/openBackhaul/core/issues/21#issuecomment-994743762) is in conflict with a later decision in [issue #28](https://github.com/openBackhaul/core/issues/28).

Decision made on [15th of December 2021](https://github.com/openBackhaul/core/issues/21#issuecomment-994743762) assumes that grouping configuration-and-switch-control is included, but in [issue #28](https://github.com/openBackhaul/core/issues/28) has been decided to prune grouping configuration-and-switch-control from the modelling.

If in [issue #29](https://github.com/openBackhaul/core/issues/29), would be decided (as proposed to the 5G-xhaul call on 28th of September 2022) to prune the following attributes from the modelling:

- fc-switch/configuration-and-switch-control
- fc-switch/internal-configuration-and-switch-control
- casc-port/encapsulating-casc-port
- clock/encapsulated-casc
- layer-protocol/configuration-and-switch-control

this issue could just be closed.
