### ISSUE TITLE
Removing embedded clock attribute from logical termination point

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#22]
Inside logical-termination-point , we have a list of clock (it is getting instantiated and not referred to any other instance)
```
list embedded-clock {
      key "local-id";
      uses clock;
      description
        "none";
    }
```
On **5G-xhaul call 15th of December 2021**, we discussed to change the type of the “embedded-clock” attribute to a leafref pointing to the clock-collection in sync-model as below. 
```
leaf-list embedded-clock {
      type leafref {
        path “/core-model:control-construct/sync-model:clock-collection/sync-model:clock/core-model:local-id";
        require-instance false;
      }
      description
        "none";
    }

```
But , the reference to a technology specific module from core-model requires an import of that referred model.Also this will cause a circular dependency.

So we came up with the following plan,
1.	**Pruning “embedded-clock”** attribute **from “logical-termination-point” in “core-model”**
2.	Including the attribute “embedded-clock” to the “sync-model” and augmenting that attribute to the “logical-termination-point” in “core-model”
3.	This “embedded-clock” attribute in sync-model will refer to the path “/core-model:control-construct/sync-model:clock-collection/sync-model:clock/core-model:local-id"

**Comment by PrathibaJee** [comment]
After removing the attribute “embedded-clock” from logical-termination-point , its impacting the referred path of the following attributes, (in the “grouping clock”)
1. encompassed-clock
2. phase-aligned-clock

Earlier the path of these attributes referred to the "embedded-clock" in LTP. 
But after pruning the "embedded-clock" , these attributes refer to the path “/core-model:clock/core-model:local-id".
We have to further discuss to handle this situation.

> Note : In core-model , clock is not used elsewhere apart from embedded-clock.

**Comment by demx8as6** [comment]
2 Options

1. remove both attributes
2. remove both attributes from CoreModel and add back by SyncModel using leaf-ref to “/core-model:control-construct/sync-model:clock-collection/sync-model:clock/core-model:local-id"

AI offline with Alex from TEF about the usage of such attributes - Parthiba, Alex, Martin

**Comment by PrathibaJee** [comment]
Based on the offline discussion with Alexander , Martin and Alex , proposing the following changes in core-model-1-4.
Alexander confirmed that the parameters are needed (currently these attributes are not used , but it may be required in future)

1. **embedded-clock** attribute in logical-termination-point will be removed from core-model. Then, this attribute will be included to **sync-model** yang model and gets augmented to the **/core-model:control-construct/core-model:logical-termination-point**. Please refer [issue#7](https://github.com/openBackhaul/synchronization/issues/7) in sync-model for further implementation details.
2. **encompassed-clock , phase-aligned-clock** attributes in "grouping clock" will be removed from core-model. These attributes will be then included to **sync-model** yang model and gets augmented to the **/core-model:control-construct/sync-model:clock-collection/sync-model:clock** . Please refer [issue#8](https://github.com/openBackhaul/synchronization/issues/8) in sync-model for further implementation details.

Alex stanku confirmed that the proposed changes are working from YANG and NETCONF-Server point of view.

**Comment by openBackhaul** [comment]
**Informal decision made during the 5G-xhaul call on 26th of January 2022:**
The following changes are dealt with as bug-fixes:

1. **embedded-clock** attribute in logical-termination-point will be removed from core-model. Then, this attribute will be included to **sync-model** yang model and gets augmented to the **/core-model:control-construct/core-model:logical-termination-point**. Please refer [issue#7](https://github.com/openBackhaul/synchronization/issues/7) in sync-model for further implementation details.
2. **encompassed-clock , phase-aligned-clock** attributes in "grouping clock" will be removed from core-model. These attributes will be then included to **sync-model** yang model and gets augmented to the **/core-model:control-construct/sync-model:clock-collection/sync-model:clock** . Please refer [issue#8](https://github.com/openBackhaul/synchronization/issues/8) in sync-model for further implementation details.

These changes will be provided in the next YANG and group members are asked to comment on the published YANG.

**Comment by openBackhaul** [comment]
Implemented as decided.
