### ISSUE TITLE
Identities for 'switch-selection-reason' are missing

### ISSUE THREAD

**Issue by DanielaSpreafico** [openBackhaul/core#23]
In the last core-model (distributed on December 22th 2021), identities for the leaf  'switch-selection-reason' extending the SWITCH_STATE_REASON base identity are missing.
The only extending identity value is SWITCH_STATE_REASON_NONE, but this is not enough to report the current reason of the switch.

Proposal is to add the following identities:
SWITCH_STATE_REASON_MANUAL, 
SWITCH_STATE_REASON_SIGNAL_FORCED,
SWITCH_STATE_REASON_SIGNAL_DEGRADE, 
SWITCH_STATE_REASON_SIGNAL_FAIL

**Comment by demx8as6** [comment]
Additional values makes sense and should be included by pruning and refactoring from CoreModel 1.2 (xslt).
Values were available before.
Identities needs to be used.

**Comment by demx8as6** [comment]
**Decision made at the 5G-xhaul call on Wednesday 26th of January 2022:**

The following 4 yang identities should by added to the CoreModel yang by "pruning and refactoring".
SWITCH_STATE_REASON_MANUAL,
SWITCH_STATE_REASON_FORCED,
SWITCH_STATE_REASON_SIGNAL_DEGRADE,
SWITCH_STATE_REASON_SIGNAL_FAIL

**Comment by PrathibaJee** [comment]
- In UML2YANG tool , the pruning and refactoring section of core-model is having the neccessary code changes to include the identities, 
  - SWITCH_STATE_REASON_MANUAL,
  - SWITCH_STATE_REASON_FORCED,
  - SWITCH_STATE_REASON_SIGNAL_DEGRADE,
  - SWITCH_STATE_REASON_SIGNAL_FAIL
- This will be available if we generate and publish a new release of the core-model-1-4.

**Comment by openBackhaul** [comment]
Implemented as decided.
