### ISSUE TITLE
New core module name?

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/core#25]
Do we need a new core module name (e.g. core-module-1-4-1) to distinguish the different versions of the core model in the OpenDaylight controller?

**Comment by demx8as6** [comment]
A new model name is only needed if there is no "backward compatibility" according to [rfc8407](https://www.rfc-editor.org/rfc/rfc8407.html)

Proposal:
The answer is "NO".  Issue to be closed.

**Comment by demx8as6** [comment]
**Decision made at the 5G-xhaul call on 28th of September 2022:**
Issue shall be closed without further actions.

Note: the yang-revision statement must be added/updated with new core-model-1-4.yang versions.
