### ISSUE TITLE
control-construct::equipment::actual-equipment::is-hot-swappable parameter to be defined in detail

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#26]
This is a consequence of the issue https://github.com/openBackhaul/equipment/issues/14

Decision on 5G-xhaul call on 29th of June 2022:

1. The description of the attribute control-construct::equipment::actual-equipment::is-hot-swappable shall be modified 
from 
"none" 
to 
"This attribute shall be set on true, if the described equipment could be inserted or removed from the running system, + (without the need of powering the system down or restarting it) + (without being damaged or causing damage to any other element in the system where the equipment is inserted/removed) + (without causing traffic interruption or an alteration on the performance of other components or parts of the system not directly supported by this equipment.) The aforementioned characteristic shall not require any manual change on other components of the system. Potential traffic interruption on the interfaces supported by the component, which is being replaced, shall not matter to the value of the is-hot-swappable attribute."

2. A new revision statement shall be added while adding the comment.

> Adding the comment and revision statement shall be done by pruning and refactoring the currently used Core IM.

**Comment by PrathibaJee** [comment]
- In UML2YANG tool , the pruning and refactoring section of core-model is having the neccessary code changes to description and the revision statement. 
- This will be available if we generate and publish a new release of the core-model-1-4.

**Comment by openBackhaul** [comment]
Implemented as decided.
