### ISSUE TITLE
Delete attributes related to configuration-and-switch-control

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#29]
As per the proposal in [core-model#issue28](https://github.com/openBackhaul/core/issues/28)  , the configuration-and-switch-control class shall be deleted. 
If this proposal is decided , then , the following attributes in core-model  will have no value and can also removed , 
1. layer-protocol/configuration-and-switch-control
2. fc/configuration-and-switch-control
3. fc/fc-switch/configuration-and-switch-control 
4. fc/fc-switch/internal-configuration-and-switch-control

Details:
The proposed 4 attributes shall be pruned from the Core modelling during the pruning and refactoring step for individualizing the Core Model.

**Comment by demx8as6** [comment]
**Decision made at the 5G-xhaul call on 28th of September 2022:**
The following 6 (_changed from 4 to 6 during an Update of the proposal on 20th of September 2022_) attributes shall be pruned from the CoreModel.uml:

- layer-protocol/configuration-and-switch-control
- fc/configuration-and-switch-control
- fc/fc-switch/configuration-and-switch-control
- fc/fc-switch/internal-configuration-and-switch-control
- clock/encapsulated-casc (_added during an Update of the proposal on 20th of September 2022_)
- casc-port/encapsulating-casc-port (_added during an Update of the proposal on 20th of September 2022_)

**Comment by openBackhaul** [comment]
Implemented as decided.
