### ISSUE TITLE
global-class: name with unexpected min-elements

### ISSUE THREAD

**Issue by michbin** [openBackhaul/core#3]
The _name_ list in the _global-class_ grouping has a `min-elements: 1` constraint which is enforced when objects are created (e.g. an _fc-port_ in an _fc_).

I would not have expected the constraint because the objects defined in the Core Model are uniquely identified by either the _uuid_ or the _local-id_ attribute. They may or may not have additional _name_ attributes.

**Comment by demx8as6** [comment]
Status:
- CoreModel.uml defines multiplcity ObjectClass "Name" with attribute name[1..*] of type NameAndValue[*].

Such a model for a name in a device model is at least questionable. There is the possibility to prune-and-refactor the core-model. - I would suggest that in the end there is the same model in yang as it was for core-model 1.2.

@openBackhaul : please comment.

**Comment by demx8as6** [comment]
Decision made on the ONF call:
https://wiki.opennetworking.org/display/OTCC/2019-10-30+5G-xHaul+Meeting+Notes 

Change min-elements from 1 to 0.

**Comment by demx8as6** [comment]
Please retest once a new core-model was delivered. 

![open-backhaul-issue3](https://user-images.githubusercontent.com/9154981/68125754-8ce7b380-ff12-11e9-9817-008ca84c5c9a.png)

**Comment by openBackhaul** [comment]
Minimum number of names has been changed to 0.
Issue can be closed.
```

  grouping name {
    list name {
      key "value-name";
      min-elements 0;
      uses name-and-value;
      description
        "List of names.";
    }
```

**Comment by openBackhaul** [comment]
For avoiding warnings during compilation the "min-elements 0;" statement has been removed.

RFC7950: "If no "min-elements" statement is present, it defaults to zero."
