### ISSUE TITLE
Modify the mandatory property of the attribute occupying-fru to true

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#30]
As per the discussion in the issue https://github.com/openBackhaul/equipment/issues/10 , the attribute occupying-fru to be made as mandatory.

```
grouping holder {
leaf occupying-fru {
mandatory "true"
type leafref {
path "/core-model:control-construct/core-model:equipment/core-model:uuid";
}
description
"The FRU that is occupying the holder.
A holder may be unoccupied in reality, but always an abstract equipment object exists.
An FRU may occupy more hat one holder (using or blocking are intentionally not distinguished here).";
}
```

To include mandatory statement , the UML2YANG tool considers the UML artifact multiplicity for scalar variables. 
If  multiplicity is 1 , then the translated leaf shall include the mandatory substatement. 
This functionality is available only for rpc parameters now. So, in the preprocessing this can be handled.

**Comment by demx8as6** [comment]
**Decision made at the 5G-xhaul call on 19th of October 2022**:
The UML2YANG tool should 
- include mandatory statement for parameter "occupyingFru" by post-processing
- the multiplicity should be "1".

Please close [Equipment #10](https://github.com/openBackhaul/equipment/issues/10) after approval.

**Comment by openBackhaul** [comment]
Implemented as decided.
