### ISSUE TITLE
Mandatory Attributes

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/core#32]
The latest UML2YANG tool will include mandatory substatement to attributes that has "Multiplicity 1 + no default values defined".
The following attributes which are formerly optional will be changed to mandatory in the upcoming YANG.

Further , if an attribute is decided to be optional , we shall handle it in the pruning-and-refactioring of coreModel.

| S.No | class / datatypes                     | attributes                 | mandatory | optional |
| :--- | :------------------------------------ | :------------------------- | :-------- | :------- |
| 1    | global-class                          | uuid                       |    X      |          |
| 2    | local-class                           | local-id                   |    X      |          |
| 3    | name-and-value-authority              | uuid                       |           |    X     |
| 4    | local-id-and-class                    | local-id                   |           |    X     |
| 5    |                                       | class-of-instance          |           |    X     |
| 6    | profile                               | profile-name               |    X      |          |
| 7    | logical-termination-point             | ltp-direction              |           |    X     |
| 8    | layer-protocol                        | termination-state          |           |    X     |
| 9    |                                       | layer-protocol-name        |    X      |          |
| 10   |                                       | lp-direction               |           |    X     |
| 11   | layer-protocol-name-and-qualifier     | layer-protocol-name        |           |    X     |
| 12   | fd-port                               | role                       |           |    X     |
| 13   |                                       | fd-port-direction          |           |    X     |
| 14   | forwarding-construct                  | layer-protocol-name        |    X      |          |
| 15   | fc-port                               | is-internal-port           |           |    X     |
| 16   |                                       | role                       |           |    X     |
| 17   |                                       | fc-port-direction          |           |    X     |
| 18   | fc-switch                             | hold-off-time              |           |    X     |
| 19   |                                       | prot-type                  |           |    X     |
| 20   |                                       | switch-selection-reason    |           |    X     |
| 21   |                                       | wait-to-restore-time       |           |    X     |
| 22   | casc-port                             | port-role                  |           |    X     |
| 23   | casc-port-role-properties             | signalling-format          |           |    X     |
| 24   |                                       | monitoring-details         |           |    X     |
| 25   |                                       | control-details            |           |    X     |
| 26   | name-and-value                        | value                      |           |    X     |
| 27   | clock                                 | run-mode                   |           |    X     |
| 28   | equipment-structure                   | category                   |           |    X     |
| 29   | equipment-type                        | type-name                  |    X      |          |
| 30   |                                       | version                    |    X	    |          |
| 31   |                                       | model-identifier           |    X      |          |
| 32   | manufacturer-properties               | manufacturer-name          |    X      |          |
| 33   |                                       | manufacturer-identifier    |    X      |          |
| 34   | holder-structure                      | holder-category            |           |    X     |
| 35   |                                       | is-captive                 |           |    X     |
| 36   |                                       | is-guided                  |           |    X     |
| 37   |                                       | is-quantised-space         |           |    X     |
| 38   | connector                             | connector-type             |           |    X     |
| 39   |                                       | role                       |           |    X     |
| 40   |                                       | orientation                |           |    X     |
| 41   |                                       | pin-layout                 |           |    X     |
| 42   | holder                                | occupying-fru              |    X      |          |
| 43   |                                       | holder-location            |           |    X     |
| 44   | position                              | relative-position          |           |    X     |
| 45   | spatial-properties-of-type            | height                     |           |    X     |
| 46   |                                       | width                      |           |    X     |
| 47   |                                       | length                     |           |    X     |
| 48   | operator-augmented-equipment-instance | asset-instance-identifier  |           |    X     |
| 49   | thermal-rating                        | thermal-rating-name        |           |    X     |
| 50   |                                       | maximum-temperature        |           |    X     |
| 51   |                                       | minimum-temperature        |           |    X     |
| 52   | power-rating                          | power-rating-name          |           |    X     |
| 53   |                                       | power-rating-value         |           |    X     |
| 54   | signal-property-rule                  | signal-property-name       |           |    X     |
| 55   |                                       | signal-property-value-rule |           |    X     |
| 56   | metaclass-class                       | metaclass-class-name       |           |    X     |
| 57   | external-managed-universal-id         | manager-identifier         |           |    X     |
| 58   |                                       | external-managed-uuid      |           |    X     |
| 59   | installed-software-component          | name                       |           |    X     |
| 60   |                                       | version                    |           |    X     |
| 61   | running-software-process              | name                       |           |    X     |
| 62   |                                       | process-id                 |           |    X     |
| 63   |                                       | run-state                  |           |    X     |
| 64   |                                       | priority                   |           |    X     |
| 65   |                                       | invoking-user              |           |    X     |
| 66   |                                       | invoking-command           |           |    X     |
| 67   |                                       | time-invoked               |           |    X     |
| 68   |                                       | description                |           |    X     |
| 69   | file                                  | size                       |           |    X     |
| 70   |                                       | checksum                   |           |    X     |
| 71   |                                       | last-modify-time           |           |    X     |
| 72   | file-system-entry                     | local-name                 |           |    X     |
| 73   |                                       | path-name                  |           |    X     |
| 74   |                                       | create-date                |           |    X     |
| 75   |                                       | is-read-only               |           |    X     |
| 76   |                                       | is-hidden                  |           |    X     |

**Comment by michbin** [comment]
Some of the listed attributes cannot be mandatory because

- they have a type which is incomplete (e.g. _role_, _pin-layout_);
- they are deprecated (e.g. _hold-off-time_, _wait-to-restore-time_);
- they are not provided by some devices (e.g. _height_, _width_, _length_, _orientation_);
- they cannot be supported by some devices (e.g. _external-managed-id_).

**Comment by PrathibaJee** [comment]
[230620 CoreModelMandatoryAttributes.xlsx](https://github.com/openBackhaul/core/files/11797282/230620.CoreModelMandatoryAttributes.xlsx)

**Comment by openBackhaul** [comment]
Michael is asked to fill in the optional column with "X".
Thorsten is asked to fill in the mandatory column with "X".

**Comment by michbin** [comment]
Filled/commented sheet:
[230620.CoreModelMandatoryAttributes.MB.xlsx](https://github.com/openBackhaul/core/files/11798164/230620.CoreModelMandatoryAttributes.MB.xlsx)

**Comment by openBackhaul** [comment]
**Decision during the 5G-xhaul call on 12th of July 2023:**
The attributes of the CoreIM shall be complemented by mandatory = true statements according to the following list.

| S.No | class / datatypes                     | attributes                 | mandatory | optional |
| :--- | :------------------------------------ | :------------------------- | :-------- | :------- |
| 1    | global-class                          | uuid                       |    X      |          |
| 2    | local-class                           | local-id                   |    X      |          |
| 3    | name-and-value-authority              | uuid                       |           |    X     |
| 4    | local-id-and-class                    | local-id                   |           |    X     |
| 5    |                                       | class-of-instance          |           |    X     |
| 6    | profile                               | profile-name               |    X      |          |
| 7    | logical-termination-point             | ltp-direction              |           |    X     |
| 8    | layer-protocol                        | termination-state          |           |    X     |
| 9    |                                       | layer-protocol-name        |    X      |          |
| 10   |                                       | lp-direction               |           |    X     |
| 11   | layer-protocol-name-and-qualifier     | layer-protocol-name        |           |    X     |
| 12   | fd-port                               | role                       |           |    X     |
| 13   |                                       | fd-port-direction          |           |    X     |
| 14   | forwarding-construct                  | layer-protocol-name        |    X      |          |
| 15   | fc-port                               | is-internal-port           |           |    X     |
| 16   |                                       | role                       |           |    X     |
| 17   |                                       | fc-port-direction          |           |    X     |
| 18   | fc-switch                             | hold-off-time              |           |    X     |
| 19   |                                       | prot-type                  |           |    X     |
| 20   |                                       | switch-selection-reason    |           |    X     |
| 21   |                                       | wait-to-restore-time       |           |    X     |
| 22   | casc-port                             | port-role                  |           |    X     |
| 23   | casc-port-role-properties             | signalling-format          |           |    X     |
| 24   |                                       | monitoring-details         |           |    X     |
| 25   |                                       | control-details            |           |    X     |
| 26   | name-and-value                        | value                      |           |    X     |
| 27   | clock                                 | run-mode                   |           |    X     |
| 28   | equipment-structure                   | category                   |           |    X     |
| 29   | equipment-type                        | type-name                  |    X      |          |
| 30   |                                       | version                    |    X	    |          |
| 31   |                                       | model-identifier           |    X      |          |
| 32   | manufacturer-properties               | manufacturer-name          |    X      |          |
| 33   |                                       | manufacturer-identifier    |    X      |          |
| 34   | holder-structure                      | holder-category            |           |    X     |
| 35   |                                       | is-captive                 |           |    X     |
| 36   |                                       | is-guided                  |           |    X     |
| 37   |                                       | is-quantised-space         |           |    X     |
| 38   | connector                             | connector-type             |           |    X     |
| 39   |                                       | role                       |           |    X     |
| 40   |                                       | orientation                |           |    X     |
| 41   |                                       | pin-layout                 |           |    X     |
| 42   | holder                                | occupying-fru              |    X      |          |
| 43   |                                       | holder-location            |           |    X     |
| 44   | position                              | relative-position          |           |    X     |
| 45   | spatial-properties-of-type            | height                     |           |    X     |
| 46   |                                       | width                      |           |    X     |
| 47   |                                       | length                     |           |    X     |
| 48   | operator-augmented-equipment-instance | asset-instance-identifier  |           |    X     |
| 49   | thermal-rating                        | thermal-rating-name        |           |    X     |
| 50   |                                       | maximum-temperature        |           |    X     |
| 51   |                                       | minimum-temperature        |           |    X     |
| 52   | power-rating                          | power-rating-name          |           |    X     |
| 53   |                                       | power-rating-value         |           |    X     |
| 54   | signal-property-rule                  | signal-property-name       |           |    X     |
| 55   |                                       | signal-property-value-rule |           |    X     |
| 56   | metaclass-class                       | metaclass-class-name       |           |    X     |
| 57   | external-managed-universal-id         | manager-identifier         |           |    X     |
| 58   |                                       | external-managed-uuid      |           |    X     |
| 59   | installed-software-component          | name                       |           |    X     |
| 60   |                                       | version                    |           |    X     |
| 61   | running-software-process              | name                       |           |    X     |
| 62   |                                       | process-id                 |           |    X     |
| 63   |                                       | run-state                  |           |    X     |
| 64   |                                       | priority                   |           |    X     |
| 65   |                                       | invoking-user              |           |    X     |
| 66   |                                       | invoking-command           |           |    X     |
| 67   |                                       | time-invoked               |           |    X     |
| 68   |                                       | description                |           |    X     |
| 69   | file                                  | size                       |           |    X     |
| 70   |                                       | checksum                   |           |    X     |
| 71   |                                       | last-modify-time           |           |    X     |
| 72   | file-system-entry                     | local-name                 |           |    X     |
| 73   |                                       | path-name                  |           |    X     |
| 74   |                                       | create-date                |           |    X     |
| 75   |                                       | is-read-only               |           |    X     |
| 76   |                                       | is-hidden                  |           |    X     |

**Comment by PrathibaJee** [comment]
Required changes are available in the tool. 
(Reference : https://github.com/OpenNetworkingFoundation/5G-xHaul/issues/51)
Changes to the attribute layer-protocol-name-and-qualifier/layer-protocol-name is handled inside the UML2YANG tool.
Apart from this, other changes are handled in the pruning and refactoring section.

**Comment by openBackhaul** [comment]
Implemented as decided.
