### ISSUE TITLE
Upgrading layerProtocolName in ForwardingDomain and ForwardingConstruct too

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/core#4]
LayerProtocol class contains the layerProtocolName attribute.
During TSP datatype of the layerProtocolName attribute has been changed from LayerProtocolNameAndQualifier to layerProtocolNameType datatype.
layerProtocolNameType (enumeration) gets loaded with a layer specific value for being able to implement a conditioned augmentation of the LayerProtocol class.

Same change should be made in the layerProtocolName attribute of the ForwardingDomain and the ForwardingConstruct classes.

Proposed Solution:
ForwardingDomain::layerProtocolName : LayerProtocolNameAndQualifier => ForwardingDomain::layerProtocolName : layerProtocolNameType 
and
ForwardingConstruct ::layerProtocolName : LayerProtocolNameAndQualifier => ForwardingConstruct ::layerProtocolName : layerProtocolNameType

**Comment by demx8as6** [comment]
All layer-protocol-name attributes are of type "layer-protocol-name-type" in revision "2019-07-09".

```
demx8as6@devmartin:~/workspace/onf/5G-xHaul/models/tools$ grep -anr -A 1 "leaf layer-protocol-name" ./distribution/core-model.yang 
957:    leaf layer-protocol-name {
958-      type layer-protocol-name-type;
--
1390:    leaf layer-protocol-name {
1391-      type layer-protocol-name-type;
--
1576:    leaf layer-protocol-name {
1577-      type layer-protocol-name-type;
demx8as6@devmartin:~/workspace/onf/5G-xHaul/models/tools$ 

```
@openBackhaul: Please close after successful test.

**Comment by openBackhaul** [comment]
Data type of layer-protocol-name has been changed to layer-protocol-name-type for LayerProtocol, ForwardingDomain and ForwardingConstruct class.
Issue can be closed.
