### ISSUE TITLE
Usage of ietf-yang-types

### ISSUE THREAD

**Issue by demx8as6** [openBackhaul/core#5]
Please use ieft-yang-types when ever possible:

Examples:
    leaf last-modify-time {
      type string; -> type: yang:date-and-time;

**Comment by openBackhaul** [comment]
Dates already made in 
https://raw.githubusercontent.com/OpenNetworkingFoundation/5G-xHaul/experimental/models/tools/distribution/core-model.yang
MacAddress, IpAddress, ObjectIdentifier and UUIDs have to be analysed and potentially translated towards ietf yang datatypes.
(Special care to be taken for universal-id datatype, which is defined in the Core IM.)

**Comment by openBackhaul** [comment]
Stepped through all "type string;" and checked for changing towards ietf-yang-types.
