### ISSUE TITLE
Link Class to be added to the Core IM YANG

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/core#8]
Link had been pruned, but is required for the VLAN Layer.

**Comment by openBackhaul** [comment]
Can't find any Core IM YANG file in my data or on any github that contains "grouping link".
So can't do copy paste.

**Comment by demx8as6** [comment]
Proposal
- Topology - links should be outside of the device yang set....

**Comment by openBackhaul** [comment]
Classes of the original ONF Core IM, which are documenting the outside-of-the-devices-topology have to be defined in one or several separate UMLs, which get translated into one or several separate YANGs.
These YANGs will augment the YANG of the Core Model, which is retrieved from the devices and solely containing classes potentially relevant to the devices.
It needs to be analyzed, whether the Core Model, which is retrieved from the devices, itself will have to be prepared for augmenting some outside-of-the-devices-topology YANG, which is comprising higher level classes of the original ONF Core IM as for example NetworkControlDomain or SdnController class.

**Comment by demx8as6** [comment]
Proposal to close the issue with the comment that topologies could be implemented outside of the SDN-Controller. 
Issue to be closed. without further activity.
